### ISSUE TITLE
css imports

### ISSUE THREAD

**Issue by Anniepoo** [jamesnvc/css_write#1]
How should one express

@import url('https://fonts.googleapis.com/css2?family=MuseoModerno:wght@800&display=swap');

???

**Comment by jamesnvc** [comment]
Oh, hm, I don't think it supports that right now; I'll take a look.

**Comment by jamesnvc** [comment]
Okay, just pushed version 1.1.0 that allows you to make a rule like `'@import'(url('http://...'))`

**Comment by Anniepoo** [comment]
Truly amazing!
